WRONG_NUMBER_OF_ARGUMENTS
Method foo() takes 3 arguments, but was invoked with 2